### ISSUE TITLE
256MB file size limit in File Manager should be removed or configurable

### ISSUE THREAD

**Issue by aleonard7872** [concretecms/bedrock#195]
At the suggestion of the ConcreteCMS forum, I'm opening the 256MB file size limit of Bedrock as an issue.

I am unable to upload any file larger than 256MB to the Concrete File Manager and it has been attributed by a forum poster as being a limit specified in Bedrock. PHP settings on my server allow for larger file uploads and I have not yet found any workarounds to allow my client to use File Manager to upload larger files. My expertise in coding is extremely elementary otherwise I would be more helpful.

**Comment by webpresso-ch** [comment]
Came over the same issue. Server Settings allow me to upload much more, but it's somewhere fixed to these 256MB sizes.

**Comment by aembler** [comment]
I suspect the problem here is that we're just not specifying anything when we initialize Dropzone for our uploading – and by default Dropzone has a 256mb limit. We should probably add a setting to the files section of the Dashboard that allows for a custom override of these, which then passes that setting to Dropzone.

**Comment by aembler** [comment]
This has been removed with this line (https://github.com/concretecms/concretecms/pull/12024)

(Removed isn't the right word, it's now 4GB)
